In [1]:
import warnings
import os
import numpy as np
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from random import sample,seed
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB

In [2]:
DATA_PATH="./"

In [3]:
train_data=np.load(f'{DATA_PATH}train.npy')
train_data.shape

(5448512, 4)

In [4]:
train_y = np.load(f'{DATA_PATH}y_train.npy')
train_y.shape

(5448512,)

# Model selection

In [9]:
train_data

array([[1.502400e+000, 2.315000e+000, 3.211427e-322, 1.592043e-318],
       [3.188900e+000, 2.784800e+000, 8.399116e-323, 2.424761e-318],
       [8.930000e-002, 3.784500e+000, 3.063207e-322, 1.259447e-318],
       ...,
       [6.805100e+000, 1.997000e+000, 8.497929e-322, 5.863818e-319],
       [6.791800e+000, 8.415000e+000, 3.952525e-323, 1.667980e-318],
       [3.332800e+000, 7.075000e-001, 9.881313e-323, 1.337880e-319]])

In [5]:
size = 40000
ixs=sample(range(0, len(train_y)), size)

In [6]:
X_train=train_data[ixs]
# df_train = pd.DataFrame(train_data[ixs],columns=['X','Y','acc','time'])
y_train = train_y[ixs]
# df_train.head()

In [7]:
model = GaussianNB()
model

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
cross_val_score(model,X_train,y_train,cv=5,verbose=1).mean()

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   52.4s finished


0.4988085482334874

In [24]:
cross_val_score(model,X,y_train,cv=5,verbose=1).mean()

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   37.7s finished


0.02533415559210489

In [20]:
x_scal = StandardScaler().fit_transform(X_train[:,2].reshape(-1,1))
x_scal

array([[-8.89e-323],
       [-3.61e-322],
       [-3.11e-322],
       ...,
       [ 4.45e-322],
       [ 9.88e-324],
       [ 5.88e-322]])

In [21]:
x_scal.reshape(len(x_scal),)

array([-8.89e-323, -3.61e-322, -3.11e-322, ...,  4.45e-322,  9.88e-324,
        5.88e-322])

In [22]:
X = np.delete(X_train, 1, axis=1)  # delete 1th column 
X

array([[6.597800e+000, 3.013800e-322, 1.829456e-318],
       [1.193000e-001, 2.964394e-323, 7.441913e-319],
       [2.091400e+000, 7.905050e-323, 1.291152e-318],
       ...,
       [6.955000e+000, 8.349709e-322, 1.967345e-318],
       [2.283300e+000, 4.001932e-322, 7.281292e-319],
       [2.318600e+000, 9.782500e-322, 1.340761e-318]])

In [23]:
X = np.insert(arr=X, obj=1, values=x_scal.reshape(len(x_scal),), axis=1)
X

array([[ 6.597800e+000, -8.893182e-323,  3.013800e-322,  1.829456e-318],
       [ 1.193000e-001, -3.606679e-322,  2.964394e-323,  7.441913e-319],
       [ 2.091400e+000, -3.112614e-322,  7.905050e-323,  1.291152e-318],
       ...,
       [ 6.955000e+000,  4.446591e-322,  8.349709e-322,  1.967345e-318],
       [ 2.283300e+000,  9.881313e-324,  4.001932e-322,  7.281292e-319],
       [ 2.318600e+000,  5.879381e-322,  9.782500e-322,  1.340761e-318]])

# Prediction

In [7]:
test_data = np.load(f'{DATA_PATH}test.npy')

In [8]:
n=len(test_data)
k = 17539
j=int(n/k)
print(f'split {n} into {j} chunks of {k} size')

split 5454629 into 311 chunks of 17539 size


In [9]:
samples=[test_data[k*i:k*(i+1)]for i in range(j)]

In [10]:
samples[0]

array([[3.781600e+000, 3.074500e+000, 1.235164e-322, 2.074542e-318],
       [4.788900e+000, 1.334600e+000, 3.656086e-322, 3.209722e-318],
       [3.188000e-001, 4.519500e+000, 3.013800e-322, 3.186911e-318],
       ...,
       [6.268700e+000, 2.548800e+000, 3.754899e-321, 2.397849e-318],
       [8.773500e+000, 6.830700e+000, 3.507866e-322, 2.837384e-318],
       [4.949500e+000, 8.405500e+000, 4.001932e-322, 3.510154e-318]])

In [ ]:
num_answers=1
a = np.zeros((n,num_answers))

i=0
probs=[]
for epoch in samples:
    print(f'epoch {i}')
    t = model.predict_proba(epoch)
    d = (-t).argsort()[:,:num_answers]
    a[k*i:k*(i+1)]=train_y[d]
    #     probs.extend(t[,d])
    i+=1

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 10
epoch 11
epoch 12
epoch 13
epoch 14
epoch 15
epoch 16
epoch 17
epoch 18
epoch 19
epoch 20
epoch 21
epoch 22
epoch 23
epoch 24
epoch 25
epoch 26
epoch 27
epoch 28
epoch 29
epoch 30
epoch 31
epoch 32
epoch 33
epoch 34
epoch 35
epoch 36
epoch 37
epoch 38
epoch 39
epoch 40
epoch 41
epoch 42
epoch 43
epoch 44
epoch 45
epoch 46
epoch 47
epoch 48
epoch 49
epoch 50
epoch 51
epoch 52
epoch 53
epoch 54
epoch 55
epoch 56
epoch 57
epoch 58
epoch 59
epoch 60
epoch 61
epoch 62
epoch 63
epoch 64
epoch 65
epoch 66
epoch 67
epoch 68
epoch 69
epoch 70
epoch 71
epoch 72
epoch 73
epoch 74
epoch 75
epoch 76
epoch 77
epoch 78
epoch 79
epoch 80
epoch 81
epoch 82
epoch 83
epoch 84
epoch 85
epoch 86
epoch 87
epoch 88
epoch 89
epoch 90
epoch 91
epoch 92
epoch 93
epoch 94
epoch 95
epoch 96
epoch 97
epoch 98
epoch 99
epoch 100
epoch 101
epoch 102
epoch 103
epoch 104
epoch 105
epoch 106
epoch 107
epoch 108
epoch 109
epoch 110


array([1832128963, 1844540942])

In [16]:
c = a.astype(int)
c[1]

array([1832128963, 1844540942])

In [17]:
i=1
with open('prediction_33.csv', 'w') as out:
    print('id,place_id', file=out)
    for p in c:
        print('%i,%s' % (i,' '.join(map(str, p))), file=out)
        i+=1

'4918556336 4356993229 4355252985'

In [38]:
t[1,d[1]]

array([0.14934259, 0.1315771 , 0.11767891])

In [ ]:
with open('prediction.csv', 'w') as out:
    print('id,place_id', file=out)
    for pair in enumerate(ans, 1):
        print('%i,%i' % pair, file=out)